@startuml
package EditorSystem
{
    !include EditorContext.puml
    !include ProjectModule.puml
    !include EditorUIModule.puml

    EditorModule <.. EditorUIModule
    EditorModule <.. ProjectModule
}
@enduml