@startuml
package ProjectModule
{
    struct ProjectConfig
    {
        -string openTime;
        -string projectPath;
        -string projectName;

        -string resourcesPath;
        -string configPath;
        -string logsPath;
        -string buildPath;

        -string editorStartWorld;
        -string gameStartWorld;

        +ProjectConfig() = default;
        +ProjectConfig(string data);

        +string getOpenTime() const;
        +string getProjectPath() const;
        
        +string getResourcesPath() const;
        +string getConfigPath() const;
        +string getLogsPath() const;
        +string getBuildPath() const;

        +string getEditorStartWorld() const;
        +string getGameStartWorld() const;

        +void setEditorStartWorld(const string& path);
    }

    class ProjectModule <<singletone>>
    {
        -ProjectConfig m_projectConfig;

        +static ProjectModule& getInstance();

        +void startup();
        +void shutdown();

        -void setupProjectEnviroment();
        -void saveProjectConfig();
    }

    ProjectModule *-- ProjectConfig
}
@enduml