@startuml UnityComponents

component [Unity] as Unity

component [Vutoria] as Vutoria {
    interface "API" as VutoriaAPI
}

component "AR System" as AR_System {
    component [AR Plane] as AR_Plane
    component [AR Camera] as AR_Camera
}

component [Name] as Name
database [Coffee Data] as Coffee_Data
database [Description Ingredients] as Description_Ingredients
component [3D Materials] as 3D_Materials
component [Mesh] as Mesh
component [CoffeeContainer] as CoffeeContainer

Unity --> Vutoria : использует
Unity --> AR_System : содержит
AR_System --> AR_Plane
AR_System --> AR_Camera
CoffeeContainer --> Name : использует
Unity --> Coffee_Data : хранит
Unity --> Description_Ingredients : хранит
Unity --> 3D_Materials : использует
Unity --> Mesh : использует