@startuml
package LuaScriptModule
{
    class LuaInterpreter
    {
        -sol::state m_luaState;

        +sol::state& getLuaState();
    }

    class LuaScriptModule <<singletone>>
    {
        -LuaScriptModule() = default;
        -LuaScriptModule& operator=(const LuaScriptModule&) = delete;
        -LuaScriptModule(const LuaScriptModule&) = delete;

        -unique_ptr<LuaInterpreter> m_luaInterp;
        
        +static LuaScriptModule& getInstance();

        +void startup();
        +void shutdown();

        +void processCommand(const string& command);
        +solstate& getLuaState();

        -void registerLoggerModule()
        -void registerEventModule();
        -void registerInputModule();
        -void registerMathTypes();
        -void registerECSModule();
        -void registerResourceModule(0;)
    }

    LuaInterpreter -right-* LuaScriptModule
}
@enduml