@startuml
left to right direction
package "RenderModule" {
    
    component AbstractRenderObjects
    component IRenderer
    component OpenGLRenderer
    component VulkanRenderer

    IRenderer <|-- OpenGLRenderer
    IRenderer <|-- VulkanRenderer

    IRenderer ..> AbstractRenderObjects : uses
}

@enduml
