@startuml
package EventModule
{
    class Event <Args...>
    {
        -mutex m_mutex;
        -int nextId_{0};
        -vector<pair<int< Handler>> m_handlers;

        +Event(const Event&) = delete;
        +Event& operator=(const Event&) = delete;
        +Event(Event&&) = delete;
        +Event& operator=(Event&&) = delete;
        +Event() = default;
        +~Event() = default;

        +using Handler = function<void(Args...)>; <<type alias>>

        +int subscribe(const Handler& handler);
        +void unsubscribe(int id);
        +void operator()(Args... args);
    }
}
@enduml