@startuml
participant "OpenGLRenderer" as Renderer
participant "RenderPassData" as Pass
participant "OpenGLShader" as Shader
participant "OpenGLMesh" as Mesh
participant "RenderObject" as Object

Renderer -> Pass : Получение batches
loop for each shader
    Renderer -> Shader : use()
    alt if passType == FINAL
        Renderer -> Shader : bindTextures()
        Renderer -> Mesh : draw() (fullscreen quad)
    else
        Renderer -> Shader : setUniformData(CameraData)
        Renderer -> Shader : setUniformData(DirectionalLightData)
        loop for each mesh
            loop for each object
                Renderer -> Shader : setUniformData(ModelMatrix)
                Renderer -> Mesh : draw()
            end
        end
    end
end

@enduml