@startuml
package GameSystem
{
    package GameModule
    {
        class Game <expands by IEngineContext>
        {
            +Game();
            +virtual ~Game();

            +void initMinor() override;
            +void initMajor() override;
            +void tick(float deltaTime) override;
            +void shutdown() override();

            -void startupGameModules();
            -void shutDownGameModules();
        }
    }
}
@enduml