@startuml

package LampyEngine {
    package EngineCore
    {
        !include CoreModules/CoreModules.puml
        !include RenderSubsystem/RenderSubsystem.puml
        !include ResourceManagementSubsystem/ResourceManagementSubsystem.puml
        !include InputInteractionSubsystem/InputInteractionSubsystem.puml
        !include GameLogicSubsystem/GameLogicSubsystem.puml
    }

    !include EditorSystem/EditorSystem.puml
    !include GameSystem/GameSystem.puml

    top to bottom direction
    CoreModules --------up> EngineCore.RenderSubsystem
    CoreModules --------up> EngineCore.ResourceManagementSubsystem
    CoreModules --------down> EngineCore.InputInteractionSubsystem
    CoreModules --------down> EngineCore.GameLogicSubsystem

    EngineCore -left> EditorSystem
    EngineCore -left> GameSystem
    
}
    
!include ProjectBrowser/ProjectBrowser.puml

LampyEngine ...left> ProjectBrowser

@enduml