name: CI Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-ubuntu-debug:
    name: Build and Test on Ubuntu (Debug)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (required for Conan)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Cache Conan Packages
        uses: actions/cache@v3
        with:
          path: ~/.conan
          key: ${{ runner.os }}-conan-${{ hashFiles('conanProfileDebugLinux') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      - name: Install Dependencies with Conan
        run: |
          conan install . --output-folder=build --build=missing --profile=./conanProfileDebugLinux --profile:build=./conanProfileDebugLinux

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.29.2'

      - name: Install Vulkan SDK and Shaderc (for glslc)
        run: |
          sudo apt-get update
          sudo apt-get install -y vulkan-sdk shaderc

      - name: Generate Project Files with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Debug

      - name: Precompile Shaders
        run: |
          glslc Source/Shaders/shader.vert -o build/vert.spv
          glslc Source/Shaders/shader.frag -o build/frag.spv

      - name: Build Project
        run: |
          cmake --build build --preset conan-debug

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure -C Debug

  build-and-test-windows-debug:
    name: Build and Test on Windows (Debug)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (required for Conan)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Cache Conan Packages
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\.conan
          key: ${{ runner.os }}-conan-${{ hashFiles('conanProfileDebugWindows') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      - name: Install CMake
        uses: lukka/get-cmake@v3.26.4

      - name: Install Vulkan SDK and Shaderc (for glslc)
        run: |
          choco install vulkan-sdk -y
          choco install shaderc -y

      - name: Install Dependencies with Conan
        run: |
          conan install . --output-folder=build --build=missing --profile=./conanProfileDebugWindows --profile:build=./conanProfileDebugWindows

      - name: Generate Project Files with CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" --fresh

      - name: Precompile Shaders
        run: |
          glslc.exe Source/Shaders/shader.vert -o build\vert.spv
          glslc.exe Source/Shaders/shader.frag -o build\frag.spv

      - name: Build Project
        run: |
          cmake --build build --preset conan-debug

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure -C Debug
