name: Build and Test LampyEngine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug]  # Вы указали, что пока работаете только с Debug

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python (required for Conan)
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Conan
      run: pip install conan

    - name: Install dependencies with Conan
      run: |
        conan profile new default --detect --force
        conan profile update settings.compiler=gcc default
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan install . --build=missing -s build_type=${{ matrix.build_type }} --settings cmake:generator=Ninja

    - name: Configure CMake
      run: |
        cd build
        cmake .. --fresh -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake"

    - name: Build project
      run: |
        cd build
        cmake --build . --preset conan-debug

    - name: Run Tests
      run: |
        ctest --test-dir ./build/ --output-on-failure -C Debug
