name: Build and Test LampyEngine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python (required for Conan)
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies for Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl-dev libgl1-mesa-dev

    - name: Install Conan
      run: pip install conan

    - name: Detect Conan Profile
      run: conan profile detect --force

    - name: Install dependencies with Conan
      run: |
        mkdir build
        conan install . --build=missing -s build_type=${{ matrix.build_type }} -c tools.system.package_manager:mode=install

    - name: Configure CMake
      run: |
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build project
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}

    - name: Run Tests
      run: |
        ctest --test-dir ./build/ --output-on-failure -C Debug
