name: CI Integration Tests on Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-ubuntu-debug:
    name: Build and Test on Ubuntu (Debug)
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Установка Python (необходим для Conan)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Установка Conan
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      # 4. Кэширование Conan пакетов
      - name: Cache Conan Packages
        uses: actions/cache@v3
        with:
          path: ~/.conan
          key: ${{ runner.os }}-conan-${{ hashFiles('conanProfileDebugLinux') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      # 5. Установка Vulkan SDK и Shaderc
      - name: Install Vulkan SDK and Shaderc
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO vulkan-sdk.tar.gz https://vulkan.lunarg.com/sdk/home/latest/linux/vulkan-sdk.tar.gz
          tar -xvf vulkan-sdk.tar.gz -C /opt/
          export VULKAN_SDK=/opt/vulkan-sdk-*/x86_64
          export PATH=$VULKAN_SDK/bin:$PATH
          export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH
          export VK_ICD_FILENAMES=$VULKAN_SDK/etc/vulkan/icd.d
          export VK_LAYER_PATH=$VULKAN_SDK/etc/vulkan/layer.d

      # 6. Установка системных зависимостей
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgl1-mesa-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb-dri3-dev \
            libxcb-xfixes0-dev \
            libxcb-present-dev \
            libxcb-randr0-dev \
            uuid-dev \
            libfontenc-dev \
            libice-dev \
            libsm-dev

      # 7. Установка зависимостей через Conan
      - name: Install Dependencies with Conan
        run: |
          conan install . \
            --output-folder=Engine/ThirdParty \
            --build=missing \
            --profile=./conanProfileDebugLinux \
            --profile:build=./conanProfileDebugLinux

      # 8. Установка CMake
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.29.2'

      # 9. Генерация файлов проекта с помощью CMake
      - name: Generate Project Files with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE="Engine/ThirdParty/conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Debug

      # 10. Предварительная компиляция шейдеров
      - name: Precompile Shaders
        run: |
          glslc Engine/Core/Shaders/shader.vert -o build/vert.spv
          glslc Engine/Core/Shaders/shader.frag -o build/frag.spv

      # 11. Сборка проекта
      - name: Build Project
        run: |
          cmake --build build --preset conan-debug

      # 12. Запуск тестов
      - name: Run Tests
        run: |
          cd build
          ctest --test-dir ./build --output-on-failure -C Debug
