name: CI Integration Tests on Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-ubuntu-debug:
    name: Build and Test on Ubuntu (Debug)
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Установка Python (необходим для Conan)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Установка Conan
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      # 4. Кэширование Conan пакетов
      - name: Cache Conan Packages
        uses: actions/cache@v3
        with:
          path: ~/.conan
          key: ${{ runner.os }}-conan-${{ hashFiles('conanProfileDebugLinux') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      # 5. Установка зависимостей через Conan
      - name: Install Dependencies with Conan
        run: |
          conan install . --output-folder=build --build=missing --profile=./conanProfileDebugLinux --profile:build=./conanProfileDebugLinux

      # 6. Установка CMake
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.29.2'

      # 7. Установка Vulkan SDK и Shaderc (для glslc)
      - name: Install Vulkan SDK and Shaderc
        run: |
          sudo apt-get update
          sudo apt-get install -y vulkan-sdk shaderc

      # 8. Генерация файлов проекта с помощью CMake
      - name: Generate Project Files with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Debug

      # 9. Предварительная компиляция шейдеров
      - name: Precompile Shaders
        run: |
          glslc Source/Shaders/shader.vert -o build/vert.spv
          glslc Source/Shaders/shader.frag -o build/frag.spv

      # 10. Сборка проекта
      - name: Build Project
        run: |
          cmake --build build --preset conan-debug

      # 11. Запуск тестов
      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure -C Debug

