name: Build and Test LampyEngine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python (required for Conan)
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Conan
      run: pip install conan

    - name: Install dependencies with Conan
      run: |
        conan profile new default --detect --force
        conan profile update settings.compiler.libcxx=libstdc++11 default
        mkdir conan_build
        cd conan_build
        conan install .. --build=missing -s build_type=${{ matrix.build_type }}

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..

    - name: Build project
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}

    - name: Run Tests
      working-directory: build
      run: ctest --output-on-failure
    - name: Run build script on Windows
